
// GET PRODUCT API

export const GET_PRODUCT_PROGRESS = "GET_PRODUCT_PROGRESS"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR"

// POST PRODUCT API

export const POST_PRODUCT_PROGRESS = "POST_PRODUCT_PROGRESS"
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_ERROR = "POST_PRODUCT_ERROR"


// DELETE PRODUCT API

export const DELETE_PRODUCT_PROGRESS = "DELETE_PRODUCT_PROGRESS"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR"


// UPDATE PRODUCT API

export const UPDATE_PRODUCT_PROGRESS = "UPDATE_PRODUCT_PROGRESS"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR"